name: design-strategic-design
description: "Design strategic patterns (bounded contexts, context maps)"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/design-strategic-design"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true