name: validate-domain-model
description: "Validate domain model consistency"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/validate-domain-model"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true