name: create-domain-service
description: "Create domain service definition"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/create-domain-service"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true