name: validate-api-contract
description: "Validate API contract consistency"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/validate-api-contract"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true