name: check-agent-language-compliance
description: "Check if agents are using ubiquitous language correctly"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/check-agent-language-compliance"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true