name: update-design-policy
description: "Update design policies for a story when requirements change or design evolves"
author: "BMad"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/update-design-policy"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

variables:
  story_dir: "{config_source}:dev_story_location"
  story_file: ""
  policy_file: ""

standalone: true