name: create-flutter-screen
description: "Create Flutter screen from design"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/create-flutter-screen"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true