name: create-aggregate
description: "Create aggregate definition"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/create-aggregate"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true