name: create-kotlin-data-class
description: "Create Kotlin data class for API DTOs"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/create-kotlin-data-class"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true