name: create-spring-component
description: "Create Spring component following patterns"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/create-spring-component"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true