name: create-value-object
description: "Create value object definition"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/create-value-object"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true