name: create-flutter-widget
description: "Create Flutter widget following design system"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/create-flutter-widget"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true