name: update-api-interface
description: "Update API interface contract"
author: "BMad"
config_source: "{project-root}/bmad/bmm/config.yaml"
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/update-api-interface"
template: false
instructions: "{installed_path}/instructions.md"
standalone: true