name: fix-korean-encoding
description: "Fix Korean encoding issues in files by converting to UTF-8 using cat heredoc method"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/fix-korean-encoding"
template: false # No template needed
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Variables and inputs
variables:
  target_file: "" # File path to fix encoding
  target_dir: "" # Directory to scan for files with encoding issues
  fix_all: false # Fix all files in directory

# Output configuration
# No output file - fixes files in place

recommended_inputs:
  - target_file: "File path to fix encoding"
  - target_dir: "Directory to scan for encoding issues"

standalone: true
