name: create-ubiquitous-language
description: "Create and define ubiquitous language for the domain. This language will be used by ALL agents in the system."
author: "BMad"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/create-ubiquitous-language"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

variables:
  language_file: "{output_folder}/ubiquitous-language/ubiquitous-language.yaml"
  domain_area: "" # Specific domain area to define

standalone: true